### ISSUE TITLE
Duplicate in package.json

### ISSUE THREAD

**Issue by mahdi-eth** [mtabatabaeifard/react-musium#15]
![Screenshot 2022-12-25 141132](https://user-images.githubusercontent.com/99660553/209464821-9375a831-253b-4bb7-80a6-38742a8650f3.jpg)

There is a duplicate in package.json which one should be deleted?

**Comment by mtabatabaeifard** [comment]
HI , I will Check It.

**Comment by mtabatabaeifard** [comment]
Fixed It ! , Thanks.

**Comment by mahdi-Eth** [comment]
By the way, you can delete **Mahdi-Ettehadnejad-branch** now, I am working on a different branch.
